app/models.py
from app import app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

DB_USER = "docker"
DB_PASS = "docker"
DB_HOST = "db"
DB_NAME = "flask_app"

app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+mysqldb://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}?charset=utf8"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
app.secret_key = "secret"

db = SQLAlchemy(app)
migrate = Migrate(app, db)

class User(UserMixin, db.Model):
    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))
    role = db.Column(db.Boolean, default=False, nullable=False)
    question_sets = db.relationship('QuestionSet', backref='user', lazy=True)
    answers = db.relationship('UserAnswer', back_populates='user', lazy=True)  

    mail = db.Column(db.String(128), unique=True)
    password = db.Column(db.String(128))

    # パスワードをハッシュ化
    def set_password(self, password):
        self.password = generate_password_hash(password)

    # 入力されたパスワードが登録されているパスワードハッシュと一致するかを確認
    def check_password(self, password):
        return check_password_hash(self.password, password)

class QuestionSet(db.Model):
    __tablename__ = 'questionset'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))
    user_id = db.Column(db.Integer, db.ForeignKey('Users.id'))
    learn_count = db.Column(db.Integer, default=0)
    good_count = db.Column(db.Integer, default=0)

    questions = db.relationship("Question", back_populates="questionset")
    answers = db.relationship('UserAnswer', back_populates='questionset', lazy=True)  

class Question(db.Model):
    __tablename__ = 'question'

    id = db.Column(db.Integer, primary_key=True)
    sentence = db.Column(db.String(128))
    choice1 = db.Column(db.String(128))
    choice2 = db.Column(db.String(128))
    choice3 = db.Column(db.String(128))
    choice4 = db.Column(db.String(128))
    correctans = db.Column(db.String(128))
    questionset_id = db.Column(db.Integer, db.ForeignKey('questionset.id'))

    questionset = db.relationship("QuestionSet", back_populates="questions")
    answers = db.relationship('UserAnswer', back_populates='question', lazy=True)  

class UserAnswer(db.Model):
    __tablename__ = 'useranswer'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('Users.id'))
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    questionset_id = db.Column(db.Integer, db.ForeignKey('questionset.id'))  
    selected_answer = db.Column(db.String(128))

    user = db.relationship("User", back_populates="answers")
    question = db.relationship("Question", back_populates="answers")
    questionset = db.relationship("QuestionSet", back_populates="answers") 

app/src/sets/views.py
from flask import Blueprint, render_template, redirect, request, url_for, abort,flash,jsonify
from flask_login import current_user
from sqlalchemy.sql import text

from app import app
from app.models import db, User, QuestionSet,Question,UserAnswer

sets = Blueprint("sets",__name__)


@sets.route("/sets", methods=["GET", "POST"])
def set_list():
  if request.method == "POST":
    set = QuestionSet(name=request.form["set_name"], user_id=current_user.id)
    db.session.add(set)
    db.session.commit()
    return redirect(url_for('sets.set_list'))
  else: # GET
    student_sets = QuestionSet.query.filter(QuestionSet.user_id == current_user.id).all()
    teachers = User.query.filter_by(role=1).all()
    return render_template("sets/sets_list.html", t=teachers, s_sets=student_sets)

@sets.route("/sets/<int:set_id>", methods=["GET"])
def set_detail(set_id):
    set = QuestionSet.query.get(set_id)
    if set is None:
        abort(404)
    answers = [question.correctans for question in set.questions]
    return render_template("sets/sets_detail.html", set=set, answers=answers)

    answers = [question.correctans for question in set.questions]
    return render_template("sets/sets_detail.html", set=set, answers=answers)

@sets.route("/sets/<int:set_id>/edit", methods=["GET", "POST"])
def set_edit(set_id):
  set = QuestionSet.query.get(set_id)
  if set.user_id != current_user.id:
     flash("他人のセットは編集できません")
     return redirect(url_for('sets.set_detail', set_id=set_id))
  else:
    if request.method == "POST":
      action = request.form.get("action", "update_set")
      if action == "update_set":
        set.name = request.form["set_name"]
        db.session.commit()
        return redirect(url_for('sets.set_edit', set_id=set_id))
      #問題の追加
      elif action == "add_question":
        question = Question(
          sentence=request.form.get("question_sentence", ""),
          choice1=request.form.get("choice1", ""),
          choice2=request.form.get("choice2", ""),
          choice3=request.form.get("choice3", ""),
          choice4=request.form.get("choice4", ""),
          correctans=request.form.get("correctans", ""),
          questionset_id=set_id)
        db.session.add(question)
        db.session.commit()
    return render_template("sets/sets_edit.html", set=set)

@sets.route('/question/<int:question_id>/delete', methods=['POST'])
def delete_question(question_id):
    question = Question.query.get(question_id)
    if question is None:
        flash('Question not found')
        return redirect(url_for('sets.set_list'))
    db.session.delete(question)
    db.session.commit()
    flash('問題を削除しました')
    return redirect(url_for('sets.set_edit', set_id=question.questionset_id))

@sets.route('/sets/<int:set_id>/delete', methods=['POST'])
def delete_set(set_id):
    set = QuestionSet.query.get(set_id)
    if set.user_id != current_user.id:
       flash('他人のセットは削除できません')
       return redirect(url_for('sets.set_list'))
    else:
      if set is None:
          flash('Set not found')
          return redirect(url_for('sets.set_list'))
      db.session.delete(set)
      db.session.commit()
      flash('セットを削除しました')
      return redirect(url_for('sets.set_list'))

#問題セットの学習開始
@sets.route("/sets/<int:set_id>/start", methods=["GET"])
def set_start(set_id):
  set = QuestionSet.query.get(set_id)
  set.learn_count = 0
  if set is None:
    abort(404)
  set.learn_count += 1
  db.session.commit()
  
  questions = Question.query.filter_by(questionset_id=set.id).all()

  # Convert each question to a dict that can be serialized to JSON
  questions_json = []
  for question in questions:
    question_dict = {
      'id': question.id,
      'sentence': question.sentence,
      'choice1': question.choice1,
      'choice2': question.choice2,
      'choice3': question.choice3,
      'choice4': question.choice4,
      'correctans': question.correctans,
      'questionset_id': question.questionset_id
    }
    questions_json.append(question_dict)
  
  return render_template("sets/sets_start.html", set=set,questions=questions_json)

@sets.route('/sets/submit_answer', methods=['POST'])
def submit_answer():
    selected_answer = request.form.get('chosenAnswer')
    question_id = request.form.get('questionId')
    questionset_id = request.form.get('questionSetId')
    user_id = current_user.get_id()

    answer = UserAnswer(user_id=user_id, questionset_id=questionset_id, question_id=question_id, selected_answer=selected_answer)
    db.session.add(answer)
    db.session.commit()

    return jsonify({'success': True})

app/templates/sets/sets_detail.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>{{ set.name }}</title>
</head>
<body>
    <a href="{{ url_for('sets.set_list') }}">問題一覧に戻る</a>
    <h1>{{ set.name }}</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
    <a href="{{ url_for('sets.set_edit', set_id=set.id) }}">編集</a>
    <a href="{{ url_for('sets.set_start', set_id=set.id) }}">始める</a>

    <!-- 教師のみ表示 -->
    {% if current_user.role == 1 %}
    <h2>生徒の解答</h2>
    <table>
        <tr>
          <th>問題</th>
          <th>回答した生徒</th>
          <th>回答した選択肢</th>
          <th>正解の選択肢</th>
        </tr>
        {% for question in set.questions %}
        {% for answer in question.answers %}
        <tr>
            <td>{{ question.sentence }}</td><!-- 問題文を表示 -->
            <td>{{ answer.user.name }}</td> <!-- 生徒の名前を表示 -->
            <td>{{ answer.selected_answer }}</td> <!-- 生徒の回答を表示 -->
            <td>{{ question.correctans }}</td> <!-- 正しい答えを表示 -->
        </tr>
        {% endfor %}
        {% endfor %}
      </table>      
    {% endif %}
</body>
</html>

app/templates/sets/sets_edit.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>問題セットの編集</title>
    <link rel="stylesheet" href="{{url_for('static', filename='edit_style.css')}}">
</head>
<body>
    <div class="container">
        <h1>問題セットの編集: {{ set.name }}</h1>
        <form action="{{ url_for('sets.set_edit', set_id=set.id) }}" method="POST">
            <input type="hidden" name="action" value="update_set">
            <div class="form-group">
                <label for="set_name">セット名:</label>
                <input type="text" name="set_name" id="set_name" value="{{ set.name }}">
                <input type="submit" value="セット名を変更">
            </div>
        </form>
        <form action="{{ url_for('sets.set_edit', set_id=set.id) }}" method="POST">
            <input type="hidden" name="action" value="add_question">
            <div class="form-group">
                <label for="question_sentence">問題文:</label>
                <input type="text" name="question_sentence" id="question_sentence">
            </div>
            <div class="form-group">
                <label for="choice1">選択肢1:</label>
                <input type="text" name="choice1" id="choice1">
            </div>
            <div class="form-group">
                <label for="choice2">選択肢2:</label>
                <input type="text" name="choice2" id="choice2">
            </div>
            <div class="form-group">
                <label for="choice3">選択肢3:</label>
                <input type="text" name="choice3" id="choice3">
            </div>
            <div class="form-group">
                <label for="choice4">選択肢4:</label>
                <input type="text" name="choice4" id="choice4">
            </div>
            <div class="form-group">
                <label for="correctans">正解の選択肢を1~4で入力:</label>
                <input type="number" name="correctans" id="correctans" min="1" max="4">
            </div>
            <div class="form-group">
                <input type="submit" value="新しい問題を追加">
            </div>
        </form>
        <a href="{{ url_for('sets.set_detail', set_id=set.id) }}">戻る(×マーク)</a>
        <h2>問題一覧</h2>
        <!-- 問題の削除を通知する -->
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        <table>
            <tr>
                <th>問題文</th>
                <th>選択肢1</th>
                <th>選択肢2</th>
                <th>選択肢3</th>
                <th>選択肢4</th>
                <th>正解</th>
                <th></th>
            </tr>
            {% for question in set.questions %}
            <tr>
                <td>{{ question.sentence }}</td>
                <td>{{ question.choice1 }}</td>
                <td>{{ question.choice2 }}</td>
                <td>{{ question.choice3 }}</td>
                <td>{{ question.choice4 }}</td>
                <td>{{ question.correctans }}</td>
                <td>
                    <form method="POST" action="{{ url_for('sets.delete_question', question_id=question.id) }}">
                        <input type="submit" value="削除">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

app/templates/sets/sets_get.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>問題一覧</title>
</head>
<body>
  <form action="/sets" method="POST">
    <div>
        セット名:<input name="set_name"></input>
    </div>
    <div>
        <input type="submit" value="作成">
    </div>
  </form>
  <h1>セット一覧</h1>
    <table>
    <tr>
      <th >セット名</th>
    </tr>
    {% for set in sets %}
    <tr>
      <td>{{ set.name }}</td>
      <td><a href="/sets/{{ set.id }}/delete" method="post">削除</a></td>
    </tr>
    {% endfor %}
    </table>
</body>

app/templates/sets/sets_list.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>問題一覧</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='sets_list_style.css')}}">
</head>
<body>
  <div class="kakoi">
      <a href="/top" class="ue">トップに戻る</a>
    <form action="/sets" method="POST">
      <div>
          <p class="moji">セット名</p>
          <input name="set_name" placeholder="セット名"></input>
      </div>
      <div class="abc">
          <input type="submit" value="問題作成" class="styled">
      </div>
    </form>

    <h1>セット一覧</h1>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
          <ul class=flashes>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
          </ul>
      {% endif %}
    {% endwith %}

    <h2>マイ問題セット</h2>
    <table>
    <tr>
      <th >セット名</th>
      <th >作成者名</th>
      <th>学習回数</th>
    </tr>
    {% for s_set in s_sets %}
    <tr>
      <td>
        <a href="{{ url_for('sets.set_detail', set_id=s_set.id) }}">{{ s_set.name }}</a>
      </td>
      <td>{{ s_set.user.name }}</td>
      <td>{{ s_set.learn_count }}</td>
      <td><a href="{{ url_for('sets.set_start', set_id=s_set.id) }}">始める</a></td>
      <td><a href="{{ url_for('sets.set_edit', set_id=s_set.id) }}">編集</a></td>
      <td>
        <form action="{{ url_for('sets.delete_set', set_id=s_set.id) }}" method="POST">
          <input type="submit" value="削除">
        </form>
      </td>
    </tr>
    {% endfor %}
    </table>

    <h2>教員の問題セット</h2>
    <table>
      <tr>
        <th>セット名</th>
        <th>作成者名</th>
        <th>学習回数</th>
      </tr>
      {% for teacher in t %}
        {% for question_set in teacher.question_sets %}
          <tr>
            <td>{{ question_set.name }}</td>
            <td>{{ teacher.name }}</td>
            <td>{{ question_set.learn_count }}</td>
            <td><a href="{{ url_for('sets.set_start', set_id=question_set.id) }}">始める</a></td>
          </tr>
        {% endfor %}
      {% endfor %}
    </table>
  </div>
</body>
</html>

app/templates/sets/sets_start.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>問題を開始</title>
    <script>
    let currentQuestionIndex = 0;
    const questions = {{ questions|tojson|safe }};
    window.onload = function() {
        showQuestion();
        document.getElementById('next').addEventListener('click', function() {
            currentQuestionIndex++;
            showQuestion();
        });
        document.getElementById('previous').addEventListener('click', function() {
            currentQuestionIndex--;
            showQuestion();
        });
        document.getElementById('submit').addEventListener('click', function() {
            checkAnswer();
        });
    };
    function showQuestion() {
        if (currentQuestionIndex < 0) {
            currentQuestionIndex = 0;
        } else if (currentQuestionIndex >= questions.length) {
            currentQuestionIndex = questions.length - 1;
        }
        const question = questions[currentQuestionIndex];
        document.getElementById('question').innerText = "問題: " + question.sentence;
        document.getElementById('label1').innerText = question.choice1;
        document.getElementById('label2').innerText = question.choice2;
        document.getElementById('label3').innerText = question.choice3;
        document.getElementById('label4').innerText = question.choice4;
        document.getElementById('questionIndex').innerText = (currentQuestionIndex + 1) + '/' + questions.length;
    }
    function checkAnswer() {
        const radios = document.getElementsByName('choices');
        let chosenAnswer;
        for(let i = 0; i < radios.length; i++) {
            if (radios[i].checked) {
                chosenAnswer = radios[i].value;
                break;
            }
        }
        const correctAnswer = questions[currentQuestionIndex].correctans;
        if (chosenAnswer == correctAnswer) {
            alert("正解！");
            
        } else {
            alert("不正解！");
        }
        submitAnswer(chosenAnswer);
    }

    function submitAnswer(answer) {
        const formData = new FormData();
        formData.append('chosenAnswer', answer);
        formData.append('questionId', questions[currentQuestionIndex].id);
        formData.append('questionSetId', questions[currentQuestionIndex].questionset_id);
        fetch('/sets/submit_answer', {
            method: 'POST',
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                console.log('Answer submitted!');
            } else {
                console.log('An error occurred.');
            }
        })
        .catch((error) => {
            console.error('Error:', error);
        });
    }
    </script>
</head>
<body>
    <h1 id="question"></h1>
    <form>
        <input type="radio" id="choice1" name="choices" value="1"><label id="label1"></label><br>
        <input type="radio" id="choice2" name="choices" value="2"><label id="label2"></label><br>
        <input type="radio" id="choice3" name="choices" value="3"><label id="label3"></label><br>
        <input type="radio" id="choice4" name="choices" value="4"><label id="label4"></label><br>
    </form>
    <p id="questionIndex"></p>
    <button id="previous">戻る</button>
    <button id="next">次へ</button>
    <button id="submit">決定</button>
    <a href="{{ url_for('sets.set_detail', set_id=set.id) }}">問題一覧に戻る(×マーク)</a>
</body>
</html>