app/src/sets/views.py
from flask import Blueprint, render_template, redirect, request, url_for, abort,flash,jsonify
from flask_login import current_user
from sqlalchemy.sql import text

from app import app
from app.models import db, User, QuestionSet,Question,UserAnswer

sets = Blueprint("sets",__name__)


@sets.route("/sets", methods=["GET", "POST"])
def set_list():
  if request.method == "POST":
    set = QuestionSet(name=request.form["set_name"], user_id=current_user.id)
    db.session.add(set)
    db.session.commit()
    return redirect(url_for('sets.set_list'))
  else: # GET
    student_sets = QuestionSet.query.filter(QuestionSet.user_id == current_user.id).all()
    teachers = User.query.filter_by(role=1).all()
    return render_template("sets/sets_list.html", t=teachers, s_sets=student_sets)

@sets.route("/sets/<int:set_id>", methods=["GET"])
def set_detail(set_id):
    set = QuestionSet.query.get(set_id)
    if set is None:
        abort(404)
    answers = [question.correctans for question in set.questions]
    return render_template("sets/sets_detail.html", set=set, answers=answers)

    answers = [question.correctans for question in set.questions]
    return render_template("sets/sets_detail.html", set=set, answers=answers)

@sets.route("/sets/<int:set_id>/edit", methods=["GET", "POST"])
def set_edit(set_id):
  set = QuestionSet.query.get(set_id)
  if set.user_id != current_user.id:
     flash("他人のセットは編集できません")
     return redirect(url_for('sets.set_detail', set_id=set_id))
  else:
    if request.method == "POST":
      action = request.form.get("action", "update_set")
      if action == "update_set":
        set.name = request.form["set_name"]
        db.session.commit()
        return redirect(url_for('sets.set_edit', set_id=set_id))
      #問題の追加
      elif action == "add_question":
        question = Question(
          sentence=request.form.get("question_sentence", ""),
          choice1=request.form.get("choice1", ""),
          choice2=request.form.get("choice2", ""),
          choice3=request.form.get("choice3", ""),
          choice4=request.form.get("choice4", ""),
          correctans=request.form.get("correctans", ""),
          questionset_id=set_id)
        db.session.add(question)
        db.session.commit()
    return render_template("sets/sets_edit.html", set=set)

@sets.route('/question/<int:question_id>/delete', methods=['POST'])
def delete_question(question_id):
    question = Question.query.get(question_id)
    if question is None:
        flash('Question not found')
        return redirect(url_for('sets.set_list'))
    db.session.delete(question)
    db.session.commit()
    flash('問題を削除しました')
    return redirect(url_for('sets.set_edit', set_id=question.questionset_id))

@sets.route('/sets/<int:set_id>/delete', methods=['POST'])
def delete_set(set_id):
    set = QuestionSet.query.get(set_id)
    if set.user_id != current_user.id:
       flash('他人のセットは削除できません')
       return redirect(url_for('sets.set_list'))
    else:
      if set is None:
          flash('Set not found')
          return redirect(url_for('sets.set_list'))
      db.session.delete(set)
      db.session.commit()
      flash('セットを削除しました')
      return redirect(url_for('sets.set_list'))

#問題セットの学習開始
@sets.route("/sets/<int:set_id>/start", methods=["GET"])
def set_start(set_id):
  set = QuestionSet.query.get(set_id)
  set.learn_count = 0
  if set is None:
    abort(404)
  set.learn_count += 1
  db.session.commit()
  
  questions = Question.query.filter_by(questionset_id=set.id).all()

  # Convert each question to a dict that can be serialized to JSON
  questions_json = []
  for question in questions:
    question_dict = {
      'id': question.id,
      'sentence': question.sentence,
      'choice1': question.choice1,
      'choice2': question.choice2,
      'choice3': question.choice3,
      'choice4': question.choice4,
      'correctans': question.correctans,
      'questionset_id': question.questionset_id
    }
    questions_json.append(question_dict)
  
  return render_template("sets/sets_start.html", set=set,questions=questions_json)

@sets.route('/sets/submit_answer', methods=['POST'])
def submit_answer():
    selected_answer = request.form.get('chosenAnswer')
    question_id = request.form.get('questionId')
    questionset_id = request.form.get('questionSetId')
    user_id = current_user.get_id()

    answer = UserAnswer(user_id=user_id, questionset_id=questionset_id, question_id=question_id, selected_answer=selected_answer)
    db.session.add(answer)
    db.session.commit()

    return jsonify({'success': True})

app/src/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required


from app.models import db, User, QuestionSet

users = Blueprint("users", __name__)

@users.route("/user/new", methods=['GET'])
def user_new_form():
    return render_template("users/user_new.html")

@users.route("/user/new",methods=['POST'])
def user_new():
    #教員であればroleカラムに1を格納
    if request.form["teacher"]:
        role = 1
    else:
        role = 0

    user = User(
        name=request.form["user_name"],
        role=role,
        mail=request.form["mail"]
    )
    user.set_password(request.form["password"])
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('logins.jump_login'))

@users.route("/teachers",methods=["GET"])
@login_required
def teacher_list():
    teachers = User.query.filter(User.role==1).all()
    return render_template("users/teacher_list.html", teachers=teachers)

@users.route("/teachers/<id>",methods=["GET"])
@login_required
def teacher_detail(id):
    teacher = User.query.filter(User.role==1, User.id==id).first()
    teacher_sets = QuestionSet.query.filter(QuestionSet.user_id==teacher.id).all()
    sets_count = len(teacher_sets)
    return render_template("users/teacher_detail.html", teacher=teacher, sets=teacher_sets, sets_count=sets_count)

#ユーザを確認するための処理（管理者のみ）
'''
@users.route("/all_users", methods=["GET"])
def all_user_get():
    users = User.query.all()
    return render_template("users/all_user.html", users=users)

@users.route("/user/<id>/delete",methods=["POST"])
def user_delete(id):
    user = User.query.filter(User.id==id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('users.all_user_get'))
'''

app/templates/users/all_user.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>セット</title>
</head>
<body>
    <table>
        <tr>
            <th >名前</th>
        </tr>
        {% for u in users %}
        <tr>
            <td>{{ u.name }}</td>
            <td>
                <form action="/user/{{ u.id }}/delete" method="POST">
                    <input type="submit" value="削除">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>

app/templates/users/teacher_detail.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>{{ teacher.name }}</title>
</head>
<body>
    <a href="{{ url_for('users.teacher_list') }}">教員一覧に戻る</a>
    <h1>{{ teacher.name }}先生</h1>
    <h2>問題セット数：{{ sets_count }}</h2>
    <table>
        <tr>
          <th >学習セット</th>
        </tr>
        {% for set in sets %}
        <tr>
          <td>{{ set.name }}</td>
          <td>
            <a href="{{ url_for('sets.set_start', set_id=set.id) }}">始める</a>
          </td>
        </tr>
        {% endfor %}
        </table>
</body>
</html>

app/templates/users/teacher_list.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>教員一覧</title>
</head>
<body>
  <a href="/top">トップに戻る</a>
  <h1>教員一覧</h1>
    <table>
    <tr>
      <th >教員名</th>
      <th >学習セット数</th>
    </tr>
    {% for teacher in teachers %}
    <tr>
      <td>
        <a href="{{ url_for('users.teacher_detail', id=teacher.id) }}">{{ teacher.name }}</a>
      </td>
      <td>問題セット数</td>
    </tr>
    {% endfor %}
    </table>
</body>
</html>

app/templates/users/user_new.html
<!DOCTYPE html>
 <html lang="jp">
 <head>
     <meta charset="UTF-8">
     <title>ユーザの作成</title>
 </head>
 <body>
     <h1>追加フォーム</h1>
     <form action="/user/new" method="POST">
         <div>名前:<input name="user_name"></input></div>
         <div>メールアドレス:<input name="mail"></input></div>
         <div>パスワード:<input type="password" name="password"></input></div>
         <div>
            教員です：<input type="checkbox" name="teacher">
        </div>
         <div>
             <input type="submit" value="送信">
             <input type="reset" value="取消">
         </div>
     </form>
 </body>